### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by dna-f** [hui-z/image_gallery_saver#152]
Hi, is Null safety migration on roadmap?
Thanks

**Comment by fzyzcjy** [comment]
looking forward to this update!

**Comment by fzyzcjy** [comment]
I have made a PR https://github.com/hui-z/image_gallery_saver/pull/153

**Comment by Ethirallan** [comment]
> I have made a PR #153

Thank you! Until the PR is merged, you can use:
```
  image_gallery_saver:
    git:
      url: https://github.com/fzyzcjy/image_gallery_saver.git
      ref: master
```
