### ISSUE TITLE
Error when build IOS 12

### ISSUE THREAD

**Issue by alfinsyahruddin** [hui-z/image_gallery_saver#174]
error: 'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'
            let newImage = image.jpegData(compressionQuality: CGFloat(quality / 100))!

error: value of optional type '[String : Any]??' not unwrapped; did you mean to use 'try!' or chain with '?'?
                return try? JSONSerialization.jsonObject(with: data, options: .mutableContainers) as? [String:Any]

**Comment by kanari3** [comment]
I'm having trouble with that error too.
Are you using CircleCI?

I have tentatively addressed this below

https://github.com/kanari3/image_gallery_saver/commit/920f0d79018e57d5a9e2c81a772524f3e4ee9f40

```yaml
#pubspec.yml
  image_gallery_saver:
    git: https://github.com/kanari3/image_gallery_saver.git
```

environment
Flutter 2.10.2
Xcode 13.1.0 and 13.3.0
CircleCI version: 2.1
