### ISSUE TITLE
Kotlin 1.5.20 is minimum since gradle plugin 7.3.0

### ISSUE THREAD

**Issue by asaarnak** [hui-z/image_gallery_saver#220]
https://developer.android.com/studio/releases/gradle-plugin#min-kotlin-version
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

**Comment by yusuphwickama** [comment]
Add to your `pubspec.yaml`
```
dependency_overrides:
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver
      ref: master
```
