### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by BrayanX44** [hui-z/image_gallery_saver#247]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':in_app_update' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21

**Comment by dennisgbp** [comment]
any solution for this problem please?

**Comment by dennisgbp** [comment]
solution using flutter 3.7.12:

pubspec.yaml

`image_gallery_saver: 
    git:
      url: https://github.com/hui-z/image_gallery_saver
      ref: master # branch name`
     
      
 android/build.gradle
 
 `classpath 'com.android.tools.build:gradle:7.2.2'`
  
  
 android/gradle/wrapper/gradle-wrapper.properties
 
 `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip`

**Comment by mkobuolys** [comment]
The solution in case this package is a transitive dependency in your project:

```
dependency_overrides:
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver
      ref: master
```

Anyway, I hope the maintainers of this package will update it pretty soon, too.
