### ISSUE TITLE
📌  Update image_gallery_saver

### ISSUE THREAD

**Issue by marwan-alhomdy** [hui-z/image_gallery_saver#378]
```
  image_gallery_saver:
    git:
      url: https://github.com/marwan-alhomdy/image_gallery_saver.git
      ref: d63b74afeb1fb248d1790540b8a397df1028f096
```
